(* ************************************************************************ *)
(*																			*)
(* OCam'OLE - OLE Automation binding for OCaml								*)
(*																			*)
(*	Excel Sample 1															*)
(*																			*)
(* (c)2002 Nicolas Cannasse													*)
(* (c)2002 Motion-Twin														*)
(* (c)2002 Lexifi															*)
(*																			*)
(* ************************************************************************ *)

(*
	Excel is generated by :
	> olegen -o excel Excel.Application
*)

open Excel
open Ocamole
open Printf

;;
let app = IApplication.application_ (IApplication.create()) in
let books = Application_.get_workbooks app in
let book = Workbooks.add books in
let sheets = Workbook_.get_worksheets (Workbook.workbook_ book) in
let sheet = Worksheet.query ~unsafe:true (Sheets.get_item sheets ~index:(VT_INT 1)) in
let isheet = Worksheet.worksheet_ sheet in

let range x = (Worksheet_.get_range isheet ~cell1:(VT_BSTR x)) in
let cell x = Range.value2 (range x) in
let font x = Range.get_font (range x) in

pset (Application_.visible app) true;

pset (cell "B2") (VT_R4 145.5);
pset (cell "B3") (VT_C_I4 (Int32.of_int 14));
pset (cell "B4") (VT_BSTR "=SUM(B2:B3)");
pset (Font.bold (font "B4")) (VT_BOOL true);
pset (Font.color (font "B4")) (VT_INT 0x600000);
let bd = Range.get_borders (range "B4") in
pset (Borders.weight bd) (VT_INT 3);

(* do no close Excel on exit *)
do_not_close()
